spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://123.123.123.123:5432/test?currentSchema=default
    connectionTimeout: 10000
    maxLifetime: 18000000
    maximumPoolSize: 10
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  sql:
    init:
      platform: org.hibernate.dialect.PostgreSQL95Dialect

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
  instances:
    myService:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1s
  instances:
    myService:
      baseConfig: default

resilience4j:
  thread-pool-bulkhead:
    instances:
      controller:
        maxThreadPoolSize: 5
        coreThreadPoolSize: 2
        queueCapacity: 10




