spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://123.123.123.123:5432/test?currentSchema=default
    connectionTimeout: 10000
    maxLifetime: 18000000
    maximumPoolSize: 10
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  sql:
    init:
      platform: org.hibernate.dialect.PostgreSQL95Dialect

profile-protection:
  dataClasses:
    - name: USER_INFO
      activeVersionName: version-1
      versions:
        - versionName: version-1
          algorithmName: Encrypt_AES_CBC_PKCS5Padding
          encryptAlgorithmName: AES/CBC/PKCS5Padding
          encryptKeyName: user
          encryptKeyVersion: 1
    - name: SAMPLE_ENCRYPTION
      activeVersionName: version-1
      versions:
        - versionName: version-1
          algorithmName: Encrypt_AES_CBC_PKCS5Padding
          encryptAlgorithmName: AES/CBC/PKCS5Padding
          encryptKeyName: user_aes
          encryptKeyVersion: 1
